# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Random Number Generator.
#

obj-y				+= lrng_pool.o lrng_aux.o \
				   lrng_sw_noise.o lrng_archrandom.o \
				   lrng_drng.o lrng_chacha20.o \
				   lrng_interfaces.o
